### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by legolasek** [NovaDrake76/KaniCasino#1]
Hey, i tried this:
```
npm install
npm run dev
```

But when I type localhost: 5173, I get an "error while connecting to server" notification
Could you write a start-up manual?

**Comment by NovaDrake76** [comment]
I made some changes at the `package.json`.

In this new version:
If you want to run only the Front-end, please run `npm install` to install the dependencies, then use `npm run dev`.
With this, you can make your changes in the front while using the online server.

If you want to run the Back-end and the Front-end, change the VITE_BASE_URL to localhost in the `.env` on the root folder, install the dependencies on the root folder and in the backend folder, then use `npm run start`.
Please note that you'll have to setup your own database to use your local backend server.

**Comment by legolasek** [comment]
how to setup database?
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at _createMongoClient (C:\Users\pawel\Desktop\KaniCasino-main\backend\node_modules\mongoose\lib\connection.js:805:11)
    at NativeConnection.openUri (C:\Users\pawel\Desktop\KaniCasino-main\backend\node_modules\mongoose\lib\connection.js:742:29)
    at Mongoose.connect (C:\Users\pawel\Desktop\KaniCasino-main\backend\node_modules\mongoose\lib\index.js:406:15)
    at Object.<anonymous> (C:\Users\pawel\Desktop\KaniCasino-main\backend\index.js:28:4)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
    
    i trying to set in .env file:
    #VITE_BASE_URL = https://kaniback.onrender.com
VITE_BASE_URL = http://localhost:5000
MONGO_URI=mongodb://username:password@host:port/database
